# Generated by Django 5.2.3 on 2025-08-26 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
                ('imagen', models.ImageField(upload_to='promociones/')),
                ('grupoCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='api.grupocategoria')),
            ],
        ),
    ]
