# Generated by Django 5.2.3 on 2025-06-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idPedido',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
