# Generated by Django 5.2.3 on 2025-08-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_promocion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocion',
            old_name='grupoCategoria',
            new_name='idproducto',
        ),
        migrations.AddField(
            model_name='promocion',
            name='precioPromocion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
