# Generated by Django 5.2.3 on 2025-08-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_grupocategoria_promocion_idproducto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='idproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='api.producto'),
        ),
    ]
