# Generated by Django 5.2.3 on 2025-08-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_promocion_idproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
