# Generated by Django 5.2.3 on 2025-08-29 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favoritos'),
        ('api', '0006_prueba'),
    ]

    operations = [
    ]
