# Generated by Django 5.2.3 on 2025-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_0003_favoritos_0006_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepago',
            name='voucher',
        ),
        migrations.AlterField(
            model_name='prueba',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pruebas/'),
        ),
    ]
