# Generated by Django 5.2.3 on 2025-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_detallepago_voucher_alter_prueba_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepago',
            name='voucher',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
