# Generated by Django 5.2.3 on 2025-08-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_detallepago_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='fechaderegistro',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prueba',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detallepago',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/'),
        ),
    ]
